### ISSUE TITLE
Project uses http redirect uri but developer portal does not allow, requires https

### ISSUE THREAD

**Issue by mscheel** [nestlabs/control-jquery#6]
When setting up a product in the developer portal the redirect URI requires a URL that starts with https://

This contradicts the README for this product which tells you to use:

http://localhost:8080/auth/nest/callback

If you do use the http URL after you get the server up and try to authenticate I see a webpage not available error, presumably because the server is not listening to https://localhost

So, the README should be updated to specify https and the project should be updated to listen at https://

Its not obvious to me how to do that.

**Comment by ryanseys** [comment]
Interesting. `http://` used to be supported until they released the new version of the developer portal as of Thursday. I'll file this as a bug because for development you should be allowed to use http.

**Comment by aurman** [comment]
It looks like we made a change to only allow localhost as a non-https redirect. It appears the new form isn't accepting it, but I'll check in let you know what the deal is.

**Comment by ryanseys** [comment]
This bug should be fixed in the Developer Portal. Try it out and let me know! :smile:

**Comment by mscheel** [comment]
I verified you can create http://localhost:8080 redirect URI's in the portal now and was able to set up the project again and make it work.  Thank you.

**Comment by ryanseys** [comment]
:+1: Thanks for keeping me updated! glad it's now working for you.
